### PR TITLE
.DS_Store banished

### PR DESCRIPTION
**Pull request by luc-demeyer**

### CODE REVIEW

**Review by sj3 — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@OCA/board it seems OCA maintainers can't perform operations here.

**Comment by simahawk** [comment]
maybe worth to sync this repo from https://github.com/OCA/oca-addons-repo-template

anyway we don't need the bot to merge such changes IMO

**Comment by pedrobaeza** [comment]
True, but I don't have neither the merge button available, so that sync is very welcome.

**Pull request merged**
